In [1]:
import numpy as np

In [2]:
print("hello world")


hello world


In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [5]:
a.ndim

2

In [6]:
a.dtype

dtype('int64')

In [7]:
b = np.array(["sky","muskan",123])

In [8]:
b.shape

(3,)

In [9]:
b.ndim

1

In [10]:
b.dtype

dtype('<U21')

In [11]:
c = np.array(["sky","muskan"])

In [12]:
c.dtype

dtype('<U6')

In [13]:
d=np.empty(2)

In [14]:
d

array([0., 0.])

In [15]:
d=np.empty(2)

In [16]:
d

array([0., 0.])

In [17]:
e= np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [18]:
e.shape

(3, 2, 4)

In [19]:
e

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])