In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5])
array2=np.array([9,8,7,6,7])
array3=np.concatenate((array1,array2))
array3

array([1, 2, 3, 4, 5, 9, 8, 7, 6, 7])

In [3]:
array4=np.array([[1,2,3,4],[5,6,7,8]])
array5=np.array([[10,11,12,13],[14,15,16,17]])
array6=np.concatenate((array4,array5),axis=0)
array6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [4]:
array7=np.concatenate((array4,array5),axis=1)
array7

array([[ 1,  2,  3,  4, 10, 11, 12, 13],
       [ 5,  6,  7,  8, 14, 15, 16, 17]])

In [5]:
array8= np.stack((array1,array2),axis=1)
array8

array([[1, 9],
       [2, 8],
       [3, 7],
       [4, 6],
       [5, 7]])

In [6]:
array9= np.stack((array1,array2),axis=0)
array9

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 7]])

In [7]:
array10= np.hstack((array1,array2))     #merge along row
array10

array([1, 2, 3, 4, 5, 9, 8, 7, 6, 7])

In [8]:
array11= np.vstack((array1,array2))     #merge along column 
array11

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 7]])

In [9]:
array12= np.dstack((array1,array2))     #merge along height
array12

array([[[1, 9],
        [2, 8],
        [3, 7],
        [4, 6],
        [5, 7]]])