In [1]:
import numpy as np

In [5]:
array1=np.array([1,2,3,4,5])
array2=np.array([9,8,7,6])
array3=np.concatenate((array1,array2))
array3

array([1, 2, 3, 4, 5, 9, 8, 7, 6])

In [6]:
array4=np.array([[1,2,3,4],[5,6,7,8]])
array5=np.array([[10,11,12,13],[14,15,16,17]])
array6=np.concatenate((array4,array5),axis=0)
array6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [7]:
array7=np.concatenate((array4,array5),axis=1)
array7

array([[ 1,  2,  3,  4, 10, 11, 12, 13],
       [ 5,  6,  7,  8, 14, 15, 16, 17]])