In [1]:
import numpy as np

In [2]:
abc= np.array([1,2,3,4])

In [3]:
abc

array([1, 2, 3, 4])

#Numpy array take less time to form and operate

In [4]:
%timeit [j**4 for j in range(1,5)]

348 ns ± 25 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [5]:
%timeit [np.arange(1,5)**4]

2.53 μs ± 177 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Creating N dimensional array in numpy

In [6]:
NDArray=np.array([1,2,3,4])
print(np.ndim(NDArray))

1


In [7]:
tenDimensionArray = np.array([1,2,3,4],ndmin=10)
print(tenDimensionArray)
print(np.ndim(tenDimensionArray))

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


Types of array we can form

In [8]:
print(np.zeros(6))
print(np.zeros((3,2)))


[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
print(np.ones(5))
print(np.ones((3,2)))
print(np.empty(4))

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0.00000000e+000 1.23417119e-311 1.23417119e-311 1.23417119e-311]


In [10]:
print(np.arange(5))

[0 1 2 3 4]


In [11]:
print(np.linspace(1,10,10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [15]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
print(np.random.rand(5))
print(np.random.rand(3,4))

[0.78500684 0.31103633 0.04690347 0.43132573 0.15170876]
[[0.59319325 0.6638227  0.07070728 0.320903  ]
 [0.59955959 0.21219613 0.43171137 0.47088983]
 [0.08590242 0.35450329 0.9911341  0.7031122 ]]


In [20]:
print(np.random.randn(5))
print(np.random.randn(3,4))

[ 0.69229297  0.39528318  1.57103297 -0.05509309 -0.15758454]
[[ 0.9592016  -0.59585594 -0.22476616  0.75830322]
 [-0.08722212  1.66006696  0.12624338 -1.76557771]
 [-0.2980639  -1.18248958 -0.80583063 -1.16351421]]


In [23]:
print(np.random.ranf(5))

[0.86444452 0.53535072 0.53076862 0.04575002 0.06779948]


In [25]:
print(np.random.randint(20,60,10))

[28 20 38 43 39 58 37 55 59 24]
