In [1]:
import numpy as np

In [2]:
abc= np.array([1,2,3,4])

In [3]:
abc

array([1, 2, 3, 4])

#Numpy array take less time to form and operate

In [5]:
%timeit [j**4 for j in range(1,5)]

409 ns ± 27.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
%timeit [np.arange(1,5)**4]

2.39 μs ± 321 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Creating N dimensional array in numpy

In [13]:
NDArray=np.array([1,2,3,4])
print(np.ndim(NDArray))

1


In [14]:
tenDimensionArray = np.array([1,2,3,4],ndmin=10)
print(tenDimensionArray)
print(np.ndim(tenDimensionArray))

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


Types of array we can form

In [19]:
print(np.zeros(6))
print(np.zeros((3,2)))


[0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
