In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5,6,7,3,2,45,3,2,7,6])

In [3]:
search1=np.where(array1==2)
search1

(array([ 1,  8, 11]),)

In [4]:
search2=np.where(array1>4)
search2

(array([ 4,  5,  6,  9, 12, 13]),)

searchsorted give the index at which the given number can be placed in sorted array

In [5]:
array2=np.array([1,2,3,4,5,7,8])

In [6]:
searchplace=np.searchsorted(array2,6)
searchplace

np.int64(5)

In [7]:
searchplace2=np.searchsorted(array2,4)
searchplace2

np.int64(3)

In [8]:
searchplace3=np.searchsorted(array2,6,side="right")
searchplace3

np.int64(5)

In [9]:
searchplace4=np.searchsorted(array2,6,side="left")
searchplace4

np.int64(5)

In [10]:
searchplace5=np.searchsorted(array2,[3,4,2],side="right")
searchplace5

array([3, 4, 2])

Sort array

In [11]:
array3=np.array([4,56,23,43,1,2,5])
sortedArray=np.sort(array3)
sortedArray

array([ 1,  2,  4,  5, 23, 43, 56])

In [12]:
array4=np.array(["n","e","a","v"])
sortedArray2=np.sort(array4)
sortedArray2

array(['a', 'e', 'n', 'v'], dtype='<U1')

In [13]:
array5=np.array([[74,56],[23,43],[1,2]])
sortedArray3=np.sort(array5)
sortedArray3

array([[56, 74],
       [23, 43],
       [ 1,  2]])

filter

In [18]:
array6=np.array(["n","e","a","v"])
requirement=[True,False,True,False]
filteredArray=array6[requirement]
filteredArray

array(['n', 'a'], dtype='<U1')