slicing method ::: 

array_name[start:stop:steps]

In [3]:
import numpy as np
array1=np.array([0,1,2,3,4,5])

In [6]:
array1[1:5:1]

array([1, 2, 3, 4])

In [9]:
array1[1:5:2]

array([1, 3])

In [10]:
array1[::2]

array([0, 2, 4])

2D Array

In [15]:
array2= np.array([[0,1,2,3,4],[9,8,7,6,5]])

In [16]:
array2[0,1:4]

array([1, 2, 3])

In [17]:
array2[1,2:3]

array([7])