copy make a copy of original array as a separate entity but view links the two array and if we change data in one it will also reflect in other

In [2]:
import numpy as np

In [3]:
array1= np.array([1,2,3,4])

In [8]:
array2=array1.copy()
array2


array([1, 2, 3, 4])

In [9]:
array3 = array1.view()
array3

array([1, 2, 3, 4])

In [11]:
array3[2]=98
array3

array([ 1,  2, 98,  4])

In [12]:
array1

array([ 1,  2, 98,  4])

In [14]:
array2[0]=17
array2

array([17,  2,  3,  4])

In [15]:
array1

array([ 1,  2, 98,  4])